### ISSUE TITLE
Spruned using 1.6GB of memory

### ISSUE THREAD

**Issue by chrisguida** [gdassori/spruned#100]
Running through [Stadicus's lightning network gist](https://gist.github.com/Stadicus/a05c3c5ac6a63cdcfe1aae2b77f17cba), tried to run everything on a 1GB machine, it ran out of memory which caused lightningd to crash every couple of minutes, so I upgraded to a 2GB machine, everything was fine for about a day, then lightningd started crashing again. 

Checked to see which programs were hogging the memory, looks like it's spruned. It's supposed to be able to run in only 128MB of ram, correct?

Thanks,

--Chris

**Comment by chrisguida** [comment]
I'm on the latest commit, btw 558b93f32ee24c01255ef34cdaa59491caa08049

**Comment by chrisguida** [comment]
Is this normal behavior or can I limit the amount of memory the program uses? @gdassori ? 

I checked in blocks_reactor.py and it seems like the default is 200 blocks. At 1MB/block, that should only be 200 MB, not 1.6GB. 

Help?

**Comment by chrisguida** [comment]
Can someone point me in the right direction as to how I might debug this? This is great software but I'm gonna need to switch to bitcoin core if this memory leak isn't addressed.

**Comment by chrisguida** [comment]
Okay cool, how do I disable the mempool, is that a command line option?

**Comment by gdassori** [comment]
try with --mempool-size=0

**Comment by chrisguida** [comment]
Great, I'll try that. Thanks!!

--Chris
