### ISSUE TITLE
Proxy mode

### ISSUE THREAD

**Issue by meeDamian** [gdassori/spruned#105]
I have a bitcoind full node pruned to 550mb. I'd like `spruned` to sit in front of it, and use it as a source of truth, while backfilling blocks that have already been pruned, and ideally crosschecking them with bitcoind.

I think that offers the best of both worlds:. The chain is self-validated, while access to archival blocks is preserved w/o the storage requirement.

**Comment by gdassori** [comment]
Yeah, you wouldn't believe but this was actually the initial design and idea behind spruned, then I ended writing an autonomous pseudo-node for fun :-)

I still think it is a great idea, but spruned wouldn't help in the purpose.
