### ISSUE TITLE
Eclair Not Supported

### ISSUE THREAD

**Issue by dmar198** [gdassori/spruned#107]
I pointed Eclair at Spruned today to see if I could get that ln implementation running. It failed with this error: "fatal error: bitcoind must have wallet support enabled"

**Comment by gdassori** [comment]
Sorry but spruned does not have wallet support.
Anyway, last time I seen, eclair had native electrum support ?

**Comment by dmar198** [comment]
> Anyway, last time I seen, eclair had native electrum support ?

Apparently, yes, they do. I did not realize that. They don't seem to advertise it much; the only thing I see about it on their github is a single-line comment in their config example. I don't see any documentation on how to set it up, but I suppose it's just setting up rpc for electrum and then modifying the eclair config to point to that instead of bitcoind. Anyway, thanks for the heads up!
