### ISSUE TITLE
LND 0.80 Failure: Method not found

### ISSUE THREAD

**Issue by supertestnet** [gdassori/spruned#108]
Today I downloaded the new 0.80 edition of LND and configured it to fetch data from spruned. It failed with this error:

"unable to start wallet: unable to retrieve best block: unable to detect btcd version: -1: Method not found"

My lnd config file has bitcoin.node=bitcoind in it, so I don't think "unable to detect btcd version" implies that it's trying to hook up to btcd instead of bitcoind. I think LND 0.80 is essentially running the command "bitcoind --version" as part of its process when starting the LND wallet. Since that method is not supported by spruned, it's giving me an error.

**Comment by delbonis** [comment]
spruned only implements a subset of the bitcoind RPC API and only definitely works with c-lightning, you might want to look into using Neutrino.

**Comment by supertestnet** [comment]
Nevermind, the problem was simply that I forgot to include my rpcuser and rpcpass in my lnd.conf.

**Comment by supertestnet** [comment]
Oops, nevermind again, putting those parameters into the conf file still did not solve the issue.
