### ISSUE TITLE
Support for testnet

### ISSUE THREAD

**Issue by askz** [gdassori/spruned#37]
Hi! Great work here! 
One of the main usage I see for this project obviously : Continuous Integration testing !
And so come : Bitcoin Tesnet

Would be glad to help in few weeks maybe, stay tuned and keep up the good work!

**Comment by gdassori** [comment]
Hi, thanks for your feedback :-)

I'm working on the test coverage right now, to ensure the current code is stable enough for an alpha; then I'll resume to develop functionalities. 
Of course at some point testnet support will come; I'm programming with also this goal in mind, without adding chain dependant code constrains that would be hard to refactor.

To see you again!

**Comment by gdassori** [comment]
wip on testnet branch: d232e246d9b8a61d608f77698443252fd8edd798

**Comment by gdassori** [comment]
Testnet supported with aacff7a30c9b834c35700d2d908befac4fc8bbdb
