### ISSUE TITLE
issue:test get_chunk fail

### ISSUE THREAD

**Issue by mhitcher** [gdassori/spruned#51]
https://github.com/gdassori/spruned/blob/aacff7a30c9b834c35700d2d908befac4fc8bbdb/spruned/daemon/electrod/electrod_connection.py#L199

https://github.com/gdassori/spruned/blob/aacff7a30c9b834c35700d2d908befac4fc8bbdb/spruned/daemon/electrod/electrod_interface.py#L125

doesn't handle correctly the None result and FAIL the test.

**Comment by gdassori** [comment]
tests was broken due peer propagation to the reactor. 
peers propagation is needed to make the reactor to track peers errors.

fixed in commit 3bf464cdd2652ce75916a0a302425b186442ca71
