### ISSUE TITLE
SPruned Runs but does not Bind on a Port

### ISSUE THREAD

**Issue by JeffVandrewJr** [gdassori/spruned#82]
I'm running spruned like this:
```
spruned --network bitcoin.testnet --rpcbind 127.0.0.1 --rpcuser=rpcuser --rpcpassword=passw0rd --rpcport=18332
```
When I run:
```
bitcoin-cli -testnet -rpcuser=rpcuser -rpcpassword=passw0rd echo 'hello world'
```

I get:
```
error: Could not connect to the server 127.0.0.1:18332

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
```

Running `sudo lsof -i -P -n` does not show spruned as bound to `127.0.0.1` or anything at all bound to port `18332`.

**Comment by gdassori** [comment]
Hi, could you please provide some details?
What Python version are you using?
How you installed spruned?
Did you see something strange in ~/.spruned/spruned .log?
Also, the --debug option may help to highlight strange behaviors.

**Comment by JeffVandrewJr** [comment]
Running Python 3.7.2

Logs all normal and on startup show the `rpcbind` flag for 127.0.0.1.

The debug flag gives a message about not being synced yet. But that wouldn't affect binding to the port, would it?

**Comment by gdassori** [comment]
Mhm, no, being not synched shouldn't affect the RPC. 

But have to admit I haven't tested it on Python 3.7, if something is broken I simply don't known, have to try by myself here first before answering this issue.

If you are hurry to try please use docker or the widely tested python 3.6.

**Comment by gdassori** [comment]
Reproduced.
Both the plyvel and aiohttp versions pinned in requirements.txt are not supported in python 3.7.

support wip: https://github.com/gdassori/spruned/tree/python3.7

**Comment by gdassori** [comment]
Deprecated python 3.5.2, that was annoying for countless reasons and forced me to stay on outdated modules. 
Travis looks ok also for Python 3.7.2 now.

**Comment by gdassori** [comment]
Hey @JeffVandrewJr, I would close that if you agree

**Comment by JeffVandrewJr** [comment]
Thanks!
