### ISSUE TITLE
bitcoin-cli getblockchain reports "couldn't parse reply from server"

### ISSUE THREAD

**Issue by dan-da** [gdassori/spruned#97]
Seems like something is wrong.  Running latest code from master.  python 3.6.

```
$ bitcoin-cli getblockcount
576178

$ bitcoin-cli getblockchaininfo
error: couldn't parse reply from server

$ bitcoin-cli getblockhash 576178
error: couldn't parse reply from server

$ bitcoin-cli getblock 000000000000000000167d3ac098dbe6812d5bc4f191b1eb2a31b5601dffaf05
error code: -5
error message:
Block not found

$ bitcoin-cli --version
Bitcoin Core RPC client version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8

$ cd spruned && git log | grep commit | head -n 1
commit e35551b2e00ac63a65c95d47b7ecb6cdb6b4b408

$ cat ~/.spruned/spruned.conf 
rpcport=28332
network=bitcoin.mainnet
```

spruned git directory is clean.  no local modifications.  any suggestions?

**Comment by gdassori** [comment]
Hello @dan-da. 
Sorry to see that.

It's hard to say what's going on, without the log file.
Could you please reproduce the bug and tail the spruned log file (into ~/.spruned/spruned.log) to report more details?
Thank you very much.

**Comment by dan-da** [comment]
I just ran all of the commands above again and tailed the log file.  None of them left any log entries.

I do see some "out of range" entries in the log  where n is greater than getblockcount.  But right now I am trying to duplicate that using getblockhash and the log line does not show up, although an "Out of range" error is reported by bitcoin-cli.

log example:
```
2019-05-15 11:32:54,349 - spruned.dependencies.connectrum - DEBUG - Error response: '{'code': 1, 'message': 'height 576,189 out of range'}'
```

bitcoin-cli example:
```
$ bitcoin-cli getblockhash 576300
error code: -8
error message:
Block height out of range
```

It puzzles me that bitcoin-cli is unable to parse responses.  I wonder if there is some debug output or other garbage in the response...

Do you know of a way that I can make a query directly to spruned and see it's raw response, without using bitcoin-cli, or instructing bitcoin-cli to show me the raw response?

**Comment by gdassori** [comment]
If you're familiar with Python, there's a small utility available into the codebase itself: 
https://github.com/gdassori/spruned/blob/master/spruned/application/utils/jsonrpc_client.py

Or, you can try as stated here to do jsonrpc with curl: 
https://bitcoin.stackexchange.com/questions/19665/json-rpc-via-curl

Anyway, I confirm that bitcoin-cli 0.17.1 works with spruned.

The out of range error (in debug mode) should be about the fallback mode which ensures on remote peers that currentheight+1 is not available yet and not related to the strange behavior you're reporting.

**Comment by dan-da** [comment]
I ended up writing [my own little jsonrpc client](https://github.com/dan-da/jsonrpc-cli) so that I could view the raw http request/response. 

this call works:
```
POST / HTTP/1.0
Accept: text/xml,application/xml,application/xhtml+xml,text/html,text/plain,image/png,image/jpeg,image/gif,*/*
Accept-Language: en-us
Host: localhost
User-Agent: Mozilla/4.0 (compatible; jsonrpc-cli HTTP Client; Linux)
Connection: Close
Content-Length: 58
Authorization: Basic cnBjdXNlcjpycGNwYXNzd29yZA==
Cookie: 

{"jsonrpc":"2.0","method":"getblockcount","id":1452027194}

HTTP/1.0 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 69
Date: Tue, 04 Jun 2019 15:21:58 GMT
Server: Python/3.5 aiohttp/3.0.0b0

{"error": null, "jsonrpc": "2.0", "id": 1452027194, "result": 579210}
```

This one fails:
```
POST / HTTP/1.0
Accept: text/xml,application/xml,application/xhtml+xml,text/html,text/plain,image/png,image/jpeg,image/gif,*/*
Accept-Language: en-us
Host: localhost
User-Agent: Mozilla/4.0 (compatible; jsonrpc-cli HTTP Client; Linux)
Connection: Close
Content-Length: 75
Authorization: Basic cnBjdXNlcjpycGNwYXNzd29yZA==
Cookie: 

{"jsonrpc":"2.0","method":"getblockhash","id":1005445973,"params":["2100"]}

HTTP/1.0 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Content-Length: 141
Date: Tue, 04 Jun 2019 15:23:10 GMT
Server: Python/3.5 aiohttp/3.0.0b0

<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```

500 Internal server error doesn't tell us much I guess.

A seperate install of spruned on another machine works fine, so I will try to re-install it from scratch on the machine with the issue.
